[BASIC]
; hidden
ENABLED=1 ; this option doesn’t do anything, added just in case, for compatibility; hidden

[SHADOW]
; hidden
; Colorful shadow
; MSAA_CUSTOM_KERNEL2=1 ; Advanced filtering (blurs colorful shadow a bit more, might be a bit more expensive); 1 or 0

[AMBIENT]
; hidden
; Colorful AO
; DYNAMIC_UPDATE2=1 ; Update colorful occlusion dynamically (with this option there’ll be more colorful ambient on ceiling if sun is hitting banners from behind); 1 or 0
