[driver_60]
OFFSET=0, -0.095, -0.1
HIDE=DRIVER:GEO_Driver_FACE, DRIVER:HELMET_69_SUB0, DRIVER:HELMET_69_SUB1
AMBIENT_MULT=0.02
ALPHA_MIN=0.1
MESH_SPLIT=MESH_SPLIT_0

[mesh_split_0]
MESHES = DRIVER:HELMET_69_SUB1
MODE = UV_REGIONS
UV_REFERENCE_SIZE = 1024, 512
UV_REGIONS_USE_SIZE = 1
UV_REGION_... = 142.1, 86.5, 110.1, 49.2
SPLIT_POSTFIX = ___helmet_split

[driver_70]
OFFSET=0, -0.065, -0.06
HIDE=DRIVER:HELMET_1975_SUB2

[driver_80]
OFFSET=0, -0.064, -0.125
HIDE=DRIVER:HELMET_1975_SUB2

[driver, driver_no_hans, driver_ocolus, driver_back, new_driver, gt]
OFFSET=0, -0.075, -0.085

[asr_driver_9x]
OFFSET=0, -0.065, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[driver_fedora]
OFFSET=0, -0.08, -0.06
HIDE=DRIVER_HELMET_plastic, DRIVER_HELMET_GLASS

[crf_driver99]
OFFSET=0, -0.059, -0.08
APPLY_ALPHA_FIX=1
HIDE=Geo_Visor

[fcr_kopecky]
OFFSET=0, -0.059, -0.0

[crf_driver_2003_bell]
OFFSET=0, -0.047, -0.07
APPLY_ALPHA_FIX=1
HIDE=crf_helmet_bell_2003_SUB5, crf_helmet_bell_2003_SUB6

[crf_driver_2003_arai_b, crf_driver_2003_arai_p]
OFFSET=0, -0.107, -0.1
APPLY_ALPHA_FIX=1
HIDE=crf_helmet_2003_arai_SUB1, crf_helmet_2003_arai_SUB2

[crf_driver_2003_arai_a]
OFFSET=0, -0.114, -0.1
APPLY_ALPHA_FIX=1
HIDE=crf_helmet_2003_arai_A_SUB1, crf_helmet_2003_arai_A_SUB2

[crf_driver_2003_arai]
OFFSET=0, -0.114, -0.1
APPLY_ALPHA_FIX=1
HIDE=g_crf_helmet_2003_arai_SUB0, g_crf_helmet_2003_arai_SUB1

[rss_formula_modern_1]
OFFSET=0, -0.065, -0.1
HIDE=DRIVER:GEO_RSS_Face, GEO_Glass_0, GEO_Glass_1, GEO_Glass_INT

[gt-m24]
OFFSET=0, -0.057, -0.13
HIDE=DRIVER:GEO_RSS_Face2, DRIVER:GEO_RSS_EYE1

[gt-m_pro]
OFFSET=0, -0.057, -0.145
HIDE=DRIVER:GEO_RSS_Face, GEO_Visor, GEO_Glass_0

; =================
; == ASR drivers ==
; =================

[asr_driver_bell_m3]
OFFSET=0, -0.090, -0.01
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_gp3_93]
OFFSET=0, -0.090, -0.09
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_x4]
OFFSET=0, -0.075, -0.08
HIDE=material:ASR_FACE
APPLY_ALPHA_FIX=1

[asr_driver_gp3_j193]
OFFSET=0, -0.080, -0.07
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_bell_m3_j193]
OFFSET=0, -0.095, -0.04
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_bell_lh93]
OFFSET=0, -0.065, -0.07
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_gp3]
OFFSET=0, -0.055, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_bell_vortex]
OFFSET=0, -0.095, -0.03
HIDE=material:VORTEX_FACE
APPLY_ALPHA_FIX=1

[asr_driver_gp3_ns]
OFFSET=0, -0.075, -0.03
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_gpa]
OFFSET=0, -0.060, -0.055
HIDE=material:GPA_FACE
APPLY_ALPHA_FIX=1

[asr_driver_senna_84]
OFFSET=0, -0.103, -0.055
HIDE=material:FACE_SENNA
APPLY_ALPHA_FIX=1

[asr_driver_bell]
OFFSET=0, -0.095, -0.06
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_88]
OFFSET=0, -0.095, -0.045
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[driver_640_1989_27]
OFFSET=0, -0.065, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[driver_640_1989_28]
OFFSET=0, -0.065, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_senna_89]
OFFSET=0, -0.096, -0.050
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_89]
OFFSET=0, -0.093, -0.06
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_rheos]
OFFSET=0, -0.055, -0.06
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_b191]
OFFSET=0, -0.085, -0.06
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[driver_fondmetal_1991]
OFFSET=0, -0.070, -0.04
HIDE=material:asr_face_9x1
APPLY_ALPHA_FIX=1

[driver_tyrrell_1991]
OFFSET=0, -0.080, -0.06
HIDE=material:_1991_Face
APPLY_ALPHA_FIX=1

[asr_driver_bt60b]
OFFSET=0, -0.080, -0.05
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_bell_afx-1_ns]
OFFSET=0, -0.085, -0.02
HIDE=material:AFX_1_FACE
APPLY_ALPHA_FIX=1

[asr_driver_bell_js37]
OFFSET=0, -0.060, -0.08
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_gp3_107]
OFFSET=0, -0.075, -0.06
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_bell_cg911b]
OFFSET=0, -0.060, -0.08
HIDE=material:ASR_FACE_9X1
APPLY_ALPHA_FIX=1

[asr_driver_bell_ns]
OFFSET=0, -0.065, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_x4_ns]
OFFSET=0, -0.065, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_bell_020b]
OFFSET=0, -0.085, -0.07
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[driver_f310_1996]
OFFSET=0, -0.075, -0.07
HIDE=material:F310_FACES
APPLY_ALPHA_FIX=1

[asr_kf1_driver]
OFFSET=0, -0.065, -0.08
HIDE=material:KF1_FACE
APPLY_ALPHA_FIX=1

[driver_ferrari_2004]
OFFSET=0, -0.075, -0.08
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_sf1_driver]
OFFSET=0, -0.065, -0.05
HIDE=material:ASR_FACE_9X
APPLY_ALPHA_FIX=1

[asr_driver_2020]
OFFSET=0, -0.065, -0.09
HIDE=material:WCEXTRA3
APPLY_ALPHA_FIX=1

[driver_asr2]
OFFSET=0, -0.035, -0.08
HIDE=material:WCEXTRA7
APPLY_ALPHA_FIX=1

[driver_asr3]
OFFSET=0, -0.035, -0.08
HIDE=material:WCEXTRA7
APPLY_ALPHA_FIX=1
