[ℹ]
FULLNAME=Other: DXGI
DESCRIPTION=Various tweaks and options for DirectX Graphics Infrastructure (DXGI).
SHORT_DESCRIPTION=Tweaks for DXGI

[COMMON]
; Common tweaks
; (independent section)
; DPI_AWARE2=1 ; DPI aware (forces AC window to be the exact resolution set in video settings despite monitor DPI setting); 1 or 0
SELECT_ADAPTER=0 ; GPU to use; 0 for Automatic, 1 for Selected monitor, NVIDIA? for NVIDIA, AMD? for AMD, Intel? for Intel
BACKGROUND_PAUSE=0 ; Idle in background (lowers FPS when AC is in background to save battery and lower CPU and GPU consumption); 0 for Disabled, 2 for 30 FPS, 1 for 2 FPS, 4 for "Pause rendering (for now, N/A online)"
; BACKGROUND_COLOR='#000000' ;; hidden
; HIDDEN_LOADING=0 ;; hidden
; ACCELERATED_EXIT2=1 ; Instantly close AC window when exiting (replays and such will be saved in background); 1 or 0
EFFICIENCY_MODE=1 ; Activate efficiency mode when idling in background; 1 or 0; new; hidden with BACKGROUND_PAUSE=0

[COMPATIBILITY]
; Compatibility tweaks
OLD_WINDOW=0 ; Old window (old method of creating a window for AC to be drawn into, misses some of new features); 1 or 0
OLD_SWAPCHAIN=0 ; Old swap chain (old method of initializing rendering, less efficient and misses some of more modern features); 1 or 0
EXCLUSIVE_FULLSCREEN=0 ; Allow exclusive fullscreen (not recommended, might cause crashes with Discord overlay); 1 or 0
ALLOW_STRETCHING=0 ; Allow uneven stretching in fullscreen (with this option disabled, aspect ratio will be conserved no matter the resolution in fullscreen); 1 or 0; hidden with EXCLUSIVE_FULLSCREEN
OLD_STRETCH=0 ; Old final stretching (new final stretching is applied with non-default pixel density, or if post-processing is disabled, but MSAA is enabled. The new one, which this checkbox would disable, is sharper than old one, and more compatible with G-sync); 1 or 0; hidden with OLD_SWAPCHAIN or EXCLUSIVE_FULLSCREEN
__HINT_BOTTOM=Using any of these options might negatively impact stability, performance and interfere with some of the features. If you’re experincing any issues, and using these options helps, please let us know.

[BASIC]
; Upgrade tweaks
ENABLED=1 ; this option doesn’t do anything, added for compatibility; hidden
ADVANCED_PACING=0 ; Pace frames better (ask driver to pause AC for a bit so that render would start at a perfect time, thus minimizing input lag); 1 or 0; new; hidden with COMPATIBILITY/OLD_SWAPCHAIN or COMPATIBILITY/EXCLUSIVE_FULLSCREEN
MAXIMUM_LATENCY_ADVANCED=2 ; Maximum latency (set to 1 for the lowest latency at the cost of FPS, or to 2 for a generally recommended value low-latency value); from 1 frame(s) to 4, round to 1; hidden with not ADVANCED_PACING or COMPATIBILITY/OLD_SWAPCHAIN or COMPATIBILITY/EXCLUSIVE_FULLSCREEN
MAXIMUM_LATENCY_BASE=0 ; Maximum latency (use 0 for default, which is usually 3); from 0 frame(s) to 6, round to 1; hidden with ADVANCED_PACING and not ( COMPATIBILITY/OLD_SWAPCHAIN or COMPATIBILITY/EXCLUSIVE_FULLSCREEN)
VSYNC_MODE=0 ; V-sync mode (experimental tweak, not available with old swap chain. Note: with new swap chain, tearing won’t ever appear again with V-sync disabled as well); 0 for "Default (might not work on Windows 11 with “Variable refresh rate” enabled in Windows graphics settings)", 1 for "Using FPS limiter logic (the best if you don’t want occasinal FPS dips, but CSP might misunderstand your monitor refresh rate)", 2 for "Wait for V-blank (has a risk of causing a frame skip)"
VSYNC_ADAPTIVE=1 ; Adaptive V-sync (pause syncing when FPS drops below display refresh rate); 1 or 0; new
SAVE_WINDOW=1 ; Save window position and size (if resized, changes resolution in AC video settings); 1 or 0; not available with COMPATIBILITY/OLD_WINDOW or COMPATIBILITY/EXCLUSIVE_FULLSCREEN
__HINT_BOTTOM=Settings related to latency and pacing have no effect in VR modes.

[WINDOW_TWEAKS]
; Window tweaks
; ; section tweaks; hidden with COMPATIBILITY/OLD_WINDOW 
CONFINE_CURSOR=0 ; Confine cursor to window (prevent mouse cursor from leaving AC window, active only if window is focused); 0 for disabled, 1 for enabled, 2 for only in fullscreen, 4 for only in VR, 3 for "in fullscreen or VR"
SET_TOPMOST=0 ; Topmost window (force AC window to always stay on top of others); 0 for disabled, 1 for enabled, 2 for only in fullscreen, 4 for only in VR, 3 for "in fullscreen or VR"
FORCE_FOCUSED=0 ; Always focused (force AC window to never lose focus); 0 for disabled, 1 for enabled, 2 for only in fullscreen, 4 for only in VR, 3 for "in fullscreen or VR"
BORDERLESS_WINDOWED=0 ; Hide window border (hide window frame for non-fullscreen state); 0 for disabled, 1 for with shadow, 2 for flat, 3 for flat & immovable; new

; [BASIC]
; ; New DXGI flip model
; ; ENABLED=1 ; Active (recommended); 1 or 0
; ALLOW_TEARING=1 ; Variable refresh rate support (make sure to disable vertical syncronization in AC video settings); 1 or 0
; __HINT_BOTTOM=DXGI flip model allows to draw directly to Desktop Window Manager buffer, speeding up windowed mode (doesn’t work in fullscreen). Requires Windows 10 to work. <url="https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-flip-model">More information</url>.

[HDR]
; HDR support (for HDR screens only)
ENABLED=0 ; Active; 1 or 0; not available with COMPATIBILITY/OLD_SWAPCHAIN
VERIFY=1 ; Verify if HDR is available (do not disable this option unless you know what you’re doing); 1 or 0
UI_GAMMA=0.45 ; UI gamma; from 0.1 to 2, per, round to 0.01
UI_BRIGHTNESS=1.7 ; UI brightness; from 0 to 4, per, round to 0.01

[HDR_YEBIS]
; HDR support with YEBIS
; ; section tweaks; hidden with not HDR/ENABLED 
USE_FILTER_VALUES=1 ; Use PP-filter HDR-related values if defined; 1 or 0; only with HDR/ENABLED
FORCE_LINEAR_FUNCTION=1 ; Force linear function for YEBIS; 1 or 0; only with HDR/ENABLED
BRIGHTNESS_ADJUSTMENT=0.2 ; YEBIS brightness; from 0 to 1, per, round to 0.01; only with HDR/ENABLED
POST_TONEMAPPING=1 ; Final tonemapping; 1 or 0; only with HDR/ENABLED
POST_GAMMA=0.45 ; Final gamma adjustment; from 0.1 to 2, per, round to 0.01; only with HDR/ENABLED
POST_BRIGHTNESS=1.2 ; Final brightness; from 0 to 4, per, round to 0.01; only with HDR/ENABLED
__HINT_BOTTOM=Although YEBIS (AC post processing framework) can process data without accuracy loss, it still clamps brightness. However, HDR displays are still limited and require tonemapping, so it’s actually useful as long as brightness is lowered before sending image to YEBIS, and raised afterwards.<br><br>Of course, it would require PP-filter settings, especially tonemapping-related, to be adjusted. With final tonemapping option enabled here, it might be better to switch YEBIS tonemapping to linear mode.

; [HDR_DIRECT]
; ; HDR support without YEBIS
; SCENE_BRIGHTNESS=1.0 ; Scene brightness; from 0 to 1, perc.
; SCENE_GAMMA=0.45 ; Scene gamma adjustment; from 0 to 1, perc.
; __HINT_BOTTOM=
