[ℹ]
FULLNAME=Simulation: Rain FX
PREVIEW=https://acstuff.club/images/modules/rain_fx.jpg
DESCRIPTION=Adds rain, still WIP.
SHORT_DESCRIPTION=Rain
ORDER=-1.8

[BASIC]
; Extension
ENABLED=1 ; Active (set to 0 to disable Rain FX); 1 or 0
AUTOSELECT_RAIN_TYRES=1 ; Select rain tyres automatically (at the start of the drive only); 1 or 0

; [TMP]
; Modules (temporary arrangement)
; USE_RAIN_RELIEF=1 ; Use relief map; 1 or 0
; USE_RAIN_MAPS=1 ; Use drop maps; 1 or 0
; USE_RAIN_PUDDLES=1 ; Use puddle maps; 1 or 0
; USE_CAR_WETNESS=1 ; Use car wetness maps; 1 or 0
; USE_CAR_WETNESS_CPU_SYNC=1 ; Sync car wetness maps to CPU; 1 or 0
; USE_RAIN_DROPS=1 ; Use rain drops; 1 or 0

[VISUAL_TWEAKS]
RAIN_MAPS_QUALITY=1 ; Rain maps quality; 0 for High, 1 for Medium, 2 for Low
DEBLUR_PAUSED_RAINDROPS=0 ; Disable rain drops blur when paused; 1 or 0
HITS_INTENSITY=1 ; Rain drop hits intensity (not the splashes in puddles, but those small short-living bursts from rain drops hitting anything but water); from 0 to 2, perc.
SNOW_MODE=1 ;; hidden

[WINDSCREEN_DROPS]
GFORCE_MULT=1 ; Multiplier for G-forces; from 0 to 3, perc.

[SCREEN_DROPS]
; Drops on screen
ENABLED=1 ; Active (set to 0 to disable drops on screen); 1 or 0
INTENSITY_MULT=1 ; Intensity multiplier; from 0 to 2, perc.
DISABLE_WITH_PHOTO_MODE=1 ; Disable with photo mode; 1 or 0
DISABLE_FOR_SCREENSHOTS=0 ; Disable for screenshots (works with accumulative screenshots); 1 or 0
STYLE_COCKPIT=DISTANT ; First person view; CLOSE for Large drops, DISTANT for Small drops, NONE for Disabled
STYLE_CHASE_CAMERA=CLOSE ; Chase cameras (the ones showing car from behing); CLOSE for Large drops, DISTANT for Small drops, NONE for Disabled
STYLE_CAR_CAMERAS=CLOSE ; Car cameras (including F6 cameras and cameras such as bumper one); CLOSE for Large drops, DISTANT for Small drops, NONE for Disabled
STYLE_FREE_CAMERA=CLOSE ; Free camera (with photo mode app visible, drops will disappear); CLOSE for Large drops, DISTANT for Small drops, NONE for Disabled
STYLE_TRACK_CAMERA=NONE ; Track camera; CLOSE for Large drops, DISTANT for Small drops, NONE for Disabled

[RACING_LINE_DEV]
; hidden
; copy these values to an online config under [RAIN_RACING_LINE_PREVIEW] section to enable racing line online
; note: new players signing it won’t see any accumulated changes, so it’s not that good of an idea to use it for a pickup server
ENABLED=1
FADING_PERIOD=600 ; seconds for racing line to go from 100% offset to 0%, pouring rain reduces time
SPEED_THRESHOLD=10, 90 ; speed threshold: cars start to have an effect at first value, full effect at second value, km/h
BODY_RADIUS=0.6, 1.2  ; car body radius: first value for inner radius with full intensity, second for fading out outer radius
BODY_MULT=0.01 ; car is removing water from the surface
WHEELS_MULT=0.03 ; wheels are removing water from the surface
SPLASH_MULT=3 ; if in deep puddles, wheels are adding water further to the side
SPREAD_MULT=20 ; if surface is dry but wheel is wet (just went through a puddle), it’ll add water 
