[ℹ]
FULLNAME=Cars: Visual
PREVIEW=https://acstuff.club/images/modules/tyres_fx.jpg
DESCRIPTION=Different visual improvements for cars, now grouped together.
SHORT_DESCRIPTION=Nicer cars
URL=https://trello.com/c/UnYfJSdj/2-tyres-fx
ORDER=-0.0999

[BASIC]
; Tyres FX
ENABLED=1 ; Enabled; 1 or 0
__HINT_BOTTOM=Adds visually deforming and damageable tyres.

[BRAKEDISC_FX]
; Brake discs
ENABLED=1 ; Enabled; 1 or 0
INITIAL=0.4 ; Initial wear; from 0 to 1, perc.
INTENSITY=1 ; Dynamic wear; from 0 to 5, perc.
__HINT_BOTTOM=Replaces brake discs shader with a new one, with dynamic wear, anisotropic lighting and new heating.

[SHADOWED_WHEELS]
; Shadowed wheels
ENABLED=1 ; Enabled; 1 or 0
__HINT_BOTTOM=Adds smooth shadows in wheel arches pretty much for free.

[FAKESHADOWSFX_BAKING]
; hidden
; Baking during loading
ENABLED2=1 ; Active (adds a bit of extra time to loading first time car is loaded, after that new more accurate shadow will be cached); 1 or 0
LIGHTS_COUNT=600 ;; hidden

; [FAKESHADOWSFX_DEPTH_BIAS]
; ; Depth bias (to avoid clipping shadows below the track)
; DEPTH_BIAS=-100 ;; from -500 to 0
; DEPTH_BIAS_CLAMP=0.0 ;; from 0 to 1, perc.
; SLOPE_SCALED_DEPTH_BIAS=-20.0 ;; from -100 to 0

[FAKESHADOWSFX_LOOK]
; hidden
; Visual params
OPACITY=1.0 ; Opacity; from 0 to 1.5, perc.
OPACITY_WEATHERFX_OVERRIDE=1 ; Allow Weather FX to override opacity; 1 or 0
CONCENTRATION=0.5 ; Concentration (0% is the more accurate value); from 0 to 1, perc.
CONCENTRATION_WEATHERFX_OVERRIDE=1 ; Allow Weather FX to override concentration; 1 or 0

[FAKESHADOWSFX_LOOK_LIGHT]
; hidden
; Light-related visual params
SHADOW_FACTOR=0.4 ; Sun light factor (takes sun light and shadows into account to allow more light to get under the car when sun is low); from 0 to 1, perc.
CONSIDER_DYNAMIC_LIGHTS_NOSHADOWS=1 ; Dynamic lights w/o shadows (take dynamic lights into account if dynamic shadows are disabled); 1 or 0
CONSIDER_DYNAMIC_LIGHTS_SHADOWS=1 ; Dynamic lights with shadows (take dynamic lights into account if dynamic shadows are enabled); 1 or 0
__HINT_BOTTOM=Point of these tweaks is to reduce brightness of fake shadow if area is lit by either sun light or dynamic lights. Without dynamic shadows, it’s better to keep fake shadow at full intensity, but if they’re enabled, it looks better with the intensity of fake shadows lowered. ;; hidden

[FAKESHADOWSFX_BODY_SHADOW]
; Fake shadows
USE_PROJECTION=1 ; properly project shadows on the ground (requires Extra FX); 1 or 0
REALIGN_SHADOW=1 ; realign shadow (helps with shadows on uneven surfaces if projection is not available, only affects player’s car as the one most likely to be on an uneven surface); 1 or 0

; DISTANCE_FADE_START=0.0 ; fade with jump, from; from 0 m to 2
; DISTANCE_FADE_END=0.7 ; fade with jump, to; from 0 m to 2

; TILT_FADE_START=0.9 ; fade when tilted, from (based on Y component aka cosine between it and vertical line); from 0 to 1, perc
; TILT_FADE_END=0.4 ; fade when tilted, to (based on Y component aka cosine between it and vertical line); from 0 to 1, perc
__HINT_BOTTOM=Tweaks for those blurry shadows under cars in overcast conditions.

[FAKESHADOWSFX_TYRE_SHADOW]
; hidden
; Wheels shadows
DISTANCE_FADE_START=0.0 ; fade with jump, from; from 0 m to 2
DISTANCE_FADE_END=0.2 ; fade with jump, to; from 0 m to 2

TILT_FADE_START=0.95 ; fade when tilted, from (based on Y component aka cosine between it and vertical line); from 0 to 1, perc
TILT_FADE_END=0.85 ; fade when tilted, to (based on Y component aka cosine between it and vertical line); from 0 to 1, perc

[EXTRAS]
; Extra visual options
DISTANT_HEADLIGHTS_GLARE2=1 ; Distant lights glare (adds a bit of glare for distant lights, experimental, might not work well with all cars); 1 or 0
OVERHEATING=1 ; Emit smoke and flames from overheated wheels (only applies when temperatures are around 300 °C); 1 or 0